------------------------------------ DROP TABLE ------------------------------------
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE USER_TABLE CASCADE CONSTRAINTS;
DROP TABLE ROLE_TABLE CASCADE CONSTRAINTS;
COMMIT;
------------------------------------ CREATE TABLE ------------------------------------
-- ORDERS
CREATE TABLE ORDERS (
ORDER_ID NUMBER(10,0) NOT NULL, 
ADDRESS VARCHAR2(255 CHAR), 
DATE_CREATED TIMESTAMP, 
LAST_UPDATED TIMESTAMP, 
ORDER_TRACKING_NUMBER VARCHAR2(255 CHAR), 
PRODUCT_ID NUMBER(10,0), 
TOTAL_PRICE DOUBLE PRECISION, 
TOTAL_QUANTITY NUMBER(10,0) NOT NULL, 
USERNAME_FK VARCHAR2(255 CHAR), 
PRODUCT_FK NUMBER(10,0), 
PRIMARY KEY (ORDER_ID));
-- PRODUCT_CATEGORY
CREATE TABLE PRODUCT_CATEGORY (
CATEGORY_NAME VARCHAR2(255 CHAR) NOT NULL, 
CATEGORY_DESCRIPTION VARCHAR2(255 CHAR), 
PRIMARY KEY (CATEGORY_NAME));
-- PRODUCTS
CREATE TABLE PRODUCTS (
ID NUMBER(10,0) NOT NULL, 
MANUFACTURER VARCHAR2(255 CHAR), 
PRODUCT_DESCRIPTION VARCHAR2(255 CHAR), 
PRODUCT_NAME VARCHAR2(255 CHAR), 
UNIT_PRICE DOUBLE PRECISION, 
UNITS_IN_STOCK NUMBER(10,0), 
PROD_CATEGORY_FK VARCHAR2(255 CHAR), 
PRIMARY KEY (ID));
-- ROLE_TABLE
CREATE TABLE ROLE_TABLE (
ROLE_NAME VARCHAR2(255 CHAR) NOT NULL, 
ROLE_DESCRIPTION VARCHAR2(255 CHAR), 
PRIMARY KEY (ROLE_NAME));
-- USER_ROLE
CREATE TABLE USER_ROLE (
USER_ID VARCHAR2(255 CHAR) NOT NULL, 
ROLE_ID VARCHAR2(255 CHAR) NOT NULL, 
PRIMARY KEY (USER_ID, ROLE_ID));
-- USER_TABLE
CREATE TABLE USER_TABLE (
USER_NAME VARCHAR2(255 CHAR) NOT NULL, 
USER_FIRST_NAME VARCHAR2(255 CHAR), 
USER_LAST_NAME VARCHAR2(255 CHAR), 
USER_PASSWORD VARCHAR2(255 CHAR), 
PRIMARY KEY (USER_NAME));
------------------------------------ ALTER TABLE ------------------------------------
ALTER TABLE ORDERS ADD CONSTRAINT FKkfx1mv96gnmuqr0w6q9jns19w FOREIGN KEY (USERNAME_FK) REFERENCES USER_TABLE;
ALTER TABLE ORDERS ADD CONSTRAINT FKi1q622r4qy2ok8ifvymf35gsy FOREIGN KEY (PRODUCT_FK) REFERENCES PRODUCTS;
ALTER TABLE PRODUCTS ADD CONSTRAINT FKjvoe7q2samx9cmdsrt5v6wl5 FOREIGN KEY (PROD_CATEGORY_FK) REFERENCES PRODUCT_CATEGORY;
ALTER TABLE USER_ROLE ADD CONSTRAINT FKgwc1k06gs7pyb1nfw7m4ghm4s FOREIGN KEY (ROLE_ID) REFERENCES ROLE_TABLE;
ALTER TABLE USER_ROLE ADD CONSTRAINT FK5cwpllhe458f6j6fb7rmhfyt2 FOREIGN KEY (USER_ID) REFERENCES USER_TABLE;
------------------------------------ SELECT ------------------------------------
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM PRODUCT_CATEGORY;
SELECT * FROM USER_TABLE;
SELECT * FROM ROLE_TABLE;
SELECT * FROM USER_ROLE;
------------------------------------ RESPOSITORY QUERIES ------------------------------------
SELECT * FROM ORDERS ORDER BY LAST_UPDATED DESC;
SELECT * FROM ORDERS ORDER BY DATE_CREATED DESC;
SELECT O.* FROM PRODUCTS P, PRODUCT_CATEGORY C, ORDERS O WHERE p.prod_category_fk = c.id AND p.id = o.product_fk ORDER BY c.category_name desc;

SELECT C.CATEGORY_NAME FROM PRODUCTS P, PRODUCT_CATEGORY C WHERE P.ID = 1 AND P.PROD_CATEGORY_FK = C.ID;

